version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "localstack-sam-app"
resolve_s3 = false
s3_prefix = "localstack-sam-app"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = []
image_repositories = []

[default.local_invoke]
[default.local_invoke.parameters]
region = "eu-west-1"

[default.build]
[default.build.parameters]
cached = true
parallel = true

[localstack]
[localstack.deploy]
[localstack.deploy.parameters]
stack_name = "localstack-sam-app"
resolve_s3 = false
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = []
s3_prefix = "localstack-sam-app"
